imports_granularity = "Crate"
edition = "2021"
hard_tabs = true
newline_style = "Unix"
enum_discrim_align_threshold = 20
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
max_width = 100
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
use_small_heuristics = "Max"
